version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout
      - run:
          name: Verify whitelist
          command: echo 1
      - run:
          name: Run Maven tests
          command: echo 1
workflows:
  version: 2
  default:
    jobs:
      - test
